name: Load test

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 03:00 UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  feed-load-test:
    name: Feed load test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Shopware
        uses: shopware/setup-shopware@main
        with:
          shopware-version: 'v6.7.12.2'
          php-version: '8.3'
          env: test
          php-extensions: pcov
          install: true

      - name: Checkout Tweakwise module
        uses: actions/checkout@v7
        with:
          path: custom/plugins/RhaeTweakwise

      - name: Install Shopware 6 Tweakwise module
        env:
          COMPOSER_AUTH: '{"github-oauth":{"github.com":"${{ secrets.GITHUB_TOKEN }}"}}'
        run: |
          composer config repositories.tweakwise.shopware6 "path" "custom/plugins/RhaeTweakwise"
          composer config allow-plugins.php-http/discovery false
          composer config minimum-stability dev
          composer require richardhaeser/sw-tweakwise --no-audit
          bin/console plugin:refresh
          bin/console plugin:install -c -a RhaeTweakwise

      - name: Run feed load tests
        run: |
          cd custom/plugins/RhaeTweakwise/
          php -d memory_limit=512M ../../../vendor/bin/phpunit --configuration phpunit.integration.xml --group load
