name: Testing code

on: [push, pull_request]

jobs:
  static:
    name: Static analysis
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        php: ['8.2', '8.3']
        experimental: [false]
        dependencies: ['lowest', 'highest']

    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180

      - name: Update Composer
        run: |
          sudo composer self-update
          composer --version
          composer config --no-plugins allow-plugins.symfony/runtime true

      - name: Install lowest dependencies with composer
        if: matrix.dependencies == 'lowest'
        run: composer update --no-ansi --no-interaction --no-progress --prefer-lowest

      - name: Install highest dependencies with composer
        if: matrix.dependencies == 'highest'
        run: composer update --no-ansi --no-interaction --no-progress

      - name: PHPStan
        run: |
          php -d memory_limit=-1 vendor/bin/phpstan analyse --configuration phpstan.neon --debug

      - name: CGL
        if: matrix.dependencies == 'highest' && matrix.php == '8.3'
        run: |
          php -d memory_limit=-1 vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --dry-run --using-cache=no --diff

      - name: PHP linting
        run: |
          php -d memory_limit=-1 vendor/bin/phplint --configuration=.phplint.yml

  unit:
    needs: static
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Setup Shopware
        uses: shopware/setup-shopware@main
        with:
          shopware-version: 'v6.7.1.1'
          php-version: 8.3
          env: test
          php-extensions: pcov
          install: true

      - name: Checkout Tweakwise module
        uses: actions/checkout@v3
        with:
          path: custom/plugins/RhaeTweakwise

      - name: Install Shopware 6 Tweakwise module
        run: |
          composer config repositories.tweakwise.shopware6 "path" "custom/plugins/RhaeTweakwise"
          composer config allow-plugins.php-http/discovery false
          composer config minimum-stability dev
          composer require richardhaeser/sw-tweakwise
          bin/console plugin:refresh
          bin/console plugin:install -c -a RhaeTweakwise

      - name: Run Tests
        run: |
          cd custom/plugins/RhaeTweakwise/
          php -d pcov.enabled=1 ../../../vendor/bin/phpunit
